name       : jsonrpc-glib
version    : 3.42.0
release    : 9
source     :
    - https://download.gnome.org/sources/jsonrpc-glib/3.42/jsonrpc-glib-3.42.0.tar.xz : 221989a57ca82a12467dc427822cd7651b0cad038140c931027bf1074208276b
license    : LGPL-2.1-only
component  : programming.library
summary    : Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
description: |
    Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - gi-docgen
    - gtk-doc
    - valadoc
patterns   :
    - docs : [/usr/share/doc/]
setup      : |
    %meson_configure -Denable_gtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
