name       : jsonrpc-glib
version    : 3.44.0
release    : 10
source     :
    - https://download.gnome.org/sources/jsonrpc-glib/3.44/jsonrpc-glib-3.44.0.tar.xz : 69406a0250d0cc5175408cae7eca80c0c6bfaefc4ae1830b354c0433bcd5ce06
license    : LGPL-2.1-only
component  : programming.library
summary    : Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
description: |
    Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - gi-docgen
    - gtk-doc
    - valadoc
patterns   :
    - docs : [/usr/share/doc/]
setup      : |
    %meson_configure -Denable_gtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
