name       : jsonrpc-glib
version    : 3.28.0
release    : 1
source     :
    - https://download.gnome.org/sources/jsonrpc-glib/3.28/jsonrpc-glib-3.28.0.tar.xz : ba0b0f05d58ba47d5938a54787b44ea875648214f032f75d4344162d8f736a25
license    : LGPL-2.1-only
component  : programming.library
summary    : Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
description: |
    Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Denable_gtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
