name       : jsonrpc-glib
version    : 3.38.0
release    : 7
source     :
    - https://download.gnome.org/sources/jsonrpc-glib/3.38/jsonrpc-glib-3.38.0.tar.xz : dc5f1914a91152b70fa8fc9a11ede13148ab4af644db27a36632388c927a8a82
license    : LGPL-2.1-only
component  : programming.library
summary    : Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
description: |
    Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Denable_gtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
