name       : jsonrpc-glib
version    : 3.32.0
release    : 3
source     :
    - https://download.gnome.org/sources/jsonrpc-glib/3.32/jsonrpc-glib-3.32.0.tar.xz : bc60aa36c8bdc9c701ad490508445633a9f3973ae0bd5bdd0633d5f6ffeea6eb
license    : LGPL-2.1-only
component  : programming.library
summary    : Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
description: |
    Jsonrpc-GLib is a library to communicate with JSON-RPC based peers in either a synchronous or asynchronous fashion.
builddeps  :
    - pkgconfig(json-glib-1.0)
    - gtk-doc
    - valadoc
setup      : |
    %meson_configure -Denable_gtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
